### ISSUE TITLE
Bower version issue>?

### ISSUE THREAD

**Issue by ashtonian** [loringdodge/ionic-ion-tinder-cards-2#3]
I get a 

```
  bower ENORESTARGET  No tag found that was able to satisfy 1.2.2
```

when trying to install via bower

**Comment by loringdodge** [comment]
Hey @Ashtonian,

I just checked out the issue and I experienced the same. Here's the error that was logged:

```
bower ionic#1.2.2           not-cached git://github.com/driftyco/ionic-bower.git#1.2.2
bower ionic#1.2.2              resolve git://github.com/driftyco/ionic-bower.git#1.2.2
bower ionic-tinder-cards-2#*    cached git://github.com/loringdodge/ionic-ion-tinder-cards-2.git#1.0.2
bower ionic-tinder-cards-2#*  validate 1.0.2 against git://github.com/loringdodge/ionic-ion-tinder-cards-2.git#*
bower collide#1.0.0-beta.3      cached git://github.com/driftyco/collide.git#1.0.0-beta.3
bower collide#1.0.0-beta.3    validate 1.0.0-beta.3 against git://github.com/driftyco/collide.git#1.0.0-beta.3
bower ionic#1.2.2         ENORESTARGET No tag found that was able to satisfy 1.2.2
```

I noticed that Ionic just updated versions from v1.2.1 to v1.2.2 about a day ago and I think that's the root of the problem and it's likely on their end. If you change your bower.json in your Ionic Project to use:

```
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.2.1"
  }
```

...then installing ionic-tinder-cards-2 via Bower will work again. Hopefully, the underlying issue is resolved here soon.

**Comment by ashtonian** [comment]
Thanks! that worked for me, hopefully ionic fixes it soon!

**Comment by ashtonian** [comment]
Closing as this was an ionic cli issue - thanks for looking into it!
